### ISSUE TITLE
after upgrading to 0.3.2 get error

### ISSUE THREAD

**Issue by aleksey-pavlov** [tagomoris/fluent-plugin-mysql#56]
after upgrading to 0.3.2 get error:

```
2018-05-16 15:24:56 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-05-16 15:24:57 +0000 chunk="56c54519cf08bd9b42180e270601ffc3" error_class=Mysql2::Error error="You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1"
  2018-05-16 15:24:56 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:131:in `_query'
  2018-05-16 15:24:56 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:131:in `block in query'
  2018-05-16 15:24:56 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:130:in `handle_interrupt'
  2018-05-16 15:24:56 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:130:in `query'
  2018-05-16 15:24:56 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-mysql-0.3.2/lib/fluent/plugin/out_mysql_bulk.rb:176:in `write'
  2018-05-16 15:24:56 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.1/lib/fluent/plugin/output.rb:1094:in `try_flush'
  2018-05-16 15:24:56 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.1/lib/fluent/plugin/output.rb:1319:in `flush_thread_run'
  2018-05-16 15:24:56 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.1/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-05-16 15:24:56 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

Config (from your example):
```
<source>
  @type http
  port 9881
</source>
<match mysql.input>
  @type mysql_bulk
  host localhost
  database test_app_development
  username root
  password root
  column_names id,user_name,created_at,updated_at
  table users
  flush_interval 10s
</match>
```

```
http://localhost:9881/mysql.input
Content-Type: application/json

{"user_name":"toyama","created_at":"2014/01/03 21:35:15","updated_at":"2014/01/03 21:35:15","dummy":"hogehoge"}
```

mysql version 5.7.17

**Comment by toyama0919** [comment]
sorry, released. 
https://rubygems.org/gems/fluent-plugin-mysql
